-- ============ payment ============
CREATE TABLE payment (
                         id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         order_id                 VARCHAR(255) NOT NULL,
                         midtrans_order_id        VARCHAR(255),
                         gross_amount             NUMERIC(38, 0) NOT NULL,
                         currency                 VARCHAR(255) NOT NULL DEFAULT 'IDR',
                         status                   VARCHAR(255) NOT NULL,
                         snap_token               VARCHAR(255),
                         snap_redirect_url        VARCHAR(512),
                         midtrans_transaction_id  VARCHAR(255),
                         payment_type             VARCHAR(255),
                         fraud_status             VARCHAR(255),
                         status_code              VARCHAR(255),
                         raw_transaction_status   VARCHAR(255),
                         status_message           VARCHAR(512),
                         transaction_time         TIMESTAMP(6),
                         expiry_at                TIMESTAMP(6),
                         paid_at                  TIMESTAMP(6),
                         attempt                  INTEGER NOT NULL DEFAULT 1,
                         version                  BIGINT NOT NULL DEFAULT 0,
                         created_date             TIMESTAMP(6) NOT NULL,
                         modified_date            TIMESTAMP(6) NOT NULL,
                         created_by               VARCHAR(255) NOT NULL,
                         modified_by              VARCHAR(255) NOT NULL,
                         CONSTRAINT uq_payment_order_id          UNIQUE (order_id),
                         CONSTRAINT uq_payment_midtrans_order_id UNIQUE (midtrans_order_id)
);

-- ============ inbox_message ============
CREATE TABLE inbox_message (
                               event_id      VARCHAR(255) PRIMARY KEY,
                               topic         VARCHAR(255),
                               created_date  TIMESTAMP(6) NOT NULL,
                               modified_date TIMESTAMP(6) NOT NULL,
                               created_by    VARCHAR(255) NOT NULL,
                               modified_by   VARCHAR(255) NOT NULL
);

-- ============ midtrans_notification_log ============
CREATE TABLE midtrans_notification_log (
                                           id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           midtrans_order_id VARCHAR(255),
                                           payload           TEXT,
                                           signature_valid   BOOLEAN,
                                           received_at       TIMESTAMP(6),
                                           created_date      TIMESTAMP(6) NOT NULL,
                                           modified_date     TIMESTAMP(6) NOT NULL,
                                           created_by        VARCHAR(255) NOT NULL,
                                           modified_by       VARCHAR(255) NOT NULL
);
CREATE INDEX ix_notiflog_midtrans_order_id ON midtrans_notification_log (midtrans_order_id);

-- ============ outbox_event ============
CREATE TABLE outbox_event (
                              id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              aggregate_type VARCHAR(255),
                              aggregate_id   VARCHAR(255),
                              event_type     VARCHAR(255),
                              topic          VARCHAR(255),
                              message_key    VARCHAR(255),
                              payload        TEXT,
                              status         VARCHAR(255) NOT NULL,
                              published_at   TIMESTAMP(6),
                              attempts       INTEGER NOT NULL DEFAULT 0,
                              created_date   TIMESTAMP(6) NOT NULL,
                              modified_date  TIMESTAMP(6) NOT NULL,
                              created_by     VARCHAR(255) NOT NULL,
                              modified_by    VARCHAR(255) NOT NULL
);
-- poller ambil PENDING terlama dulu
CREATE INDEX ix_outbox_pending ON outbox_event (created_date) WHERE status = 'PENDING';
